FROM python:3.10-slim

# প্রয়োজনীয় টুলস ইনস্টল
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# বট রান করা
CMD ["python", "main.py"]
